package employee.api.demo.dtos;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import jakarta.validation.constraints.Min;


public class AddEmployeeDto {

    //@NotBlank is only for string
    //@NotNull(message = "Employee's ID can't be blank")
    //Dont generate validator annotations (e.g.@NotBlank & @NotNull) for autogenerated attribs (e.g. id)

    @NotBlank
    private String firstName;

    private String midName;

    @NotBlank
    private String lastName;

    @NotBlank
    private String email;

    private String phone;
    private String address;

    private String employmentType;
    private String workType;

    @Min(0)
    private Integer hoursPerWeek;
    private LocalDate startDate;
    private LocalDate finishDate;

    private boolean onGoing;

    public AddEmployeeDto(){

    }


public String getFirstName() {
    return firstName;
}

public void setFirstName(String firstName) {
    this.firstName = firstName;
}

public String getMidName() {
    return midName;
}

public void setMidName(String midName) {
    this.midName = midName;
}

public String getLastName() {
    return lastName;
}

public void setLastName(String lastName) {
    this.lastName = lastName;
}

public String getEmail() {
    return email;
}

public void setEmail(String email) {
    this.email = email;
}

public String getPhone() {
    return phone;
}

public void setPhone(String phone) {
    this.phone = phone;
}

public String getAddress() {
    return address;
}

public void setAddress(String address) {
    this.address = address;
}

public String getEmploymentType() {
    return employmentType;
}

public void setEmploymentType(String employmentType) {
    this.employmentType = employmentType;
}

public String getWorkType() {
    return workType;
}

public void setWorkType(String workType) {
    this.workType = workType;
}

public Integer getHoursPerWeek() {
    return hoursPerWeek;
}

public void setHoursPerWeek(Integer hoursPerWeek) {
    this.hoursPerWeek = hoursPerWeek;
}

public LocalDate getStartDate() {
    return startDate;
}

public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
}

public LocalDate getFinishDate() {
    return finishDate;
}

public void setFinishDate(LocalDate finishDate) {
    this.finishDate = finishDate;
}

public boolean getOnGoing() {
    return onGoing;
}

public void setOnGoing(boolean onGoing) {
    this.onGoing = onGoing;
}
}
